In [1]:
import numpy as np

In [2]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [3]:
data2 = [0.1,5,4,12,0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [4]:
a1.dtype

dtype('int32')

In [5]:
a2.dtype

dtype('float64')

In [6]:
np.array([0.5,2,0.01,8])

array([0.5 , 2.  , 0.01, 8.  ])

In [8]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [16]:
b2 = np.arange(5)
b2.shape

(5,)

In [17]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.linspace(0, np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.array(['1.5','0.62','2','3.14','3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [25]:
str_a1 = np.array(['1.567','0.123','5.123','9','8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [26]:
str_a1.dtype

dtype('<U5')

In [27]:
num_a1.dtype

dtype('float64')

In [28]:
str_a2 = np.array(['1','3','5','7','9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [29]:
str_a2.dtype

dtype('<U1')

In [30]:
num_a2.dtype

dtype('int32')

In [31]:
num_f1 = np.array([10,21,0.549,4.75,5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [32]:
num_f1.dtype

dtype('float64')

In [33]:
num_i1.dtype

dtype('int32')

In [34]:
np.random.rand(2,3)

array([[0.69304621, 0.59536468, 0.49956158],
       [0.4993945 , 0.14540167, 0.43814409]])

In [35]:
np.random.rand()

0.8207733607716301

In [37]:
np.random.rand(2,3,4)

array([[[0.11114137, 0.53846751, 0.87159243, 0.35103688],
        [0.7480857 , 0.11718313, 0.63418229, 0.42798731],
        [0.49167527, 0.57802512, 0.74572495, 0.57793612]],

       [[0.20938103, 0.95091326, 0.48623217, 0.82418946],
        [0.85637638, 0.29911994, 0.69258076, 0.68750578],
        [0.02799558, 0.83972916, 0.45987898, 0.0083628 ]]])

In [38]:
np.random.randint(10, size=(3,4))
np.random.randint(1,30)

14

### 배열의 연산

In [39]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [40]:
arr1 +arr2

array([11, 22, 33, 44])

In [41]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [42]:
arr2 *2

array([2, 4, 6, 8])

In [43]:
arr2 **2

array([ 1,  4,  9, 16], dtype=int32)

In [44]:
arr1 *arr2

array([ 10,  40,  90, 160])

In [45]:
arr1/ arr2

array([10., 10., 10., 10.])

In [46]:
arr1/(arr2 **2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [47]:
arr1> 20

array([False, False,  True,  True])

In [48]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [49]:
[arr3.sum(),arr3.mean()]

[10, 2.0]

In [50]:
[arr3.std(),arr3.var()]

[1.4142135623730951, 2.0]

In [51]:
[arr3.min(),arr3.max()]

[0, 4]

In [53]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [54]:
arr4.cumsum()   # 누적합

array([ 1,  3,  6, 10], dtype=int32)

In [56]:
arr4.cumprod()  # 누적곱

array([ 1,  2,  6, 24], dtype=int32)

### 행렬 연산

In [58]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [59]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [60]:
A.dot(B)  #행렬의 곱

array([[0, 1],
       [6, 7]])

In [61]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [63]:
np.transpose(A)    #전치 행렬

array([[0, 2],
       [1, 3]])

In [64]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [67]:
np.linalg.inv(A)    #역행렬 구하기

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [68]:
np.linalg.det(A)   #행렬식 구하기

-2.0

### 배열의 인덱싱과 슬라이싱

In [69]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [70]:
a1[0]

0

In [71]:
a1[4]

40

In [72]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [73]:
a1[[1,3,4]]

array([10, 30, 40])

In [74]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [75]:
a2[0,2]

30

In [77]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [78]:
a2[1]

array([40, 50, 60])

In [79]:
a2[1] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [80]:
a2[1] = [47,57,67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [81]:
a2[[0,2],[0,1]]

array([10, 80])

In [82]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [83]:
a[(a%2) == 0]

array([2, 4, 6])

### 배열의 슬라이싱

In [84]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [85]:
b1[:3]

array([ 0, 10, 20])

In [86]:
b1[2:]

array([20, 30, 40, 50])

In [87]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [88]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [89]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [90]:
b2[1:3,1:3]

array([[50, 60],
       [80, 90]])

In [91]:
b2[:3,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [92]:
b2[1][0:2]

array([40, 50])

In [93]:
b2[0:2,1:3] = np.array([[25,35],[55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

### 구조적 데이터 생성하기

In [94]:
import pandas as pd

In [95]:
s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [96]:
s1.index
print(s1.index)

RangeIndex(start=0, stop=5, step=1)


In [97]:
s1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [98]:
s2 = pd.Series(['a','b','c',1,2,3])
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [99]:
import numpy as np

s3 = pd.Series([np.nan,10,30])
s3

0     NaN
1    10.0
2    30.0
dtype: float64

In [100]:
index_date = ['2018-10-07','2018-10-08','2018-10-09','2018-10-10']
s4 = pd.Series([200,195,np.nan,205],index=index_date)
s4

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
dtype: float64

In [101]:
s5 = pd.Series({'국어':100,'영어':95,'수학':90})
s5

국어    100
영어     95
수학     90
dtype: int64

### DataFrame을 활용한 데이터 생성

In [102]:
import pandas as pd

pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [103]:
import numpy as np
import pandas as pd

data_list = np.array([[10,20,30],[40,50,60],[70,80,90]])
pd.DataFrame(data_list)

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [104]:
import numpy as np
import pandas as pd

data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
index_date = pd.date_range('2019-09-01',periods=4)
columns_list = ['A','B','C']
pd.DataFrame(data,index=index_date,columns = columns_list)

A   B   C
2019-09-01   1   2   3
2019-09-02   4   5   6
2019-09-03   7   8   9
2019-09-04  10  11  12

In [105]:
table_data = {'연도':[2015,2016,2017,2016,2017],
             '지사':['한국','한국','미국','한국','미국'],
              '고객 수':[200,250,450,300,500]}
table_data

{'연도': [2015, 2016, 2017, 2016, 2017],
 '지사': ['한국', '한국', '미국', '한국', '미국'],
 '고객 수': [200, 250, 450, 300, 500]}

In [106]:
pd.DataFrame(table_data)

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2017  미국   450
3  2016  한국   300
4  2017  미국   500

In [107]:
df = pd.DataFrame(table_data, columns =['연도','지사','고객 수'])
df

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2017  미국   450
3  2016  한국   300
4  2017  미국   500

In [108]:
table_data1 = {'A':[1,2,3,4,5],
               'B':[10,20,30,40,50],
               'C':[100,200,300,400,500]}
df1 = pd.DataFrame(table_data1)
df1

A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [110]:
table_data2 = {'A':[6,7,8],
               'B':[60,70,80],
                'C':[600,700,800]}
df2 = pd.DataFrame(table_data2)
df2

A   B    C
0  6  60  600
1  7  70  700
2  8  80  800

In [111]:
df1 +df2

A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN

In [112]:
table_data3 = {'봄':[256.5,264.3,215.9,223.2,312.8],
               '여름':[770.6,567.5,599.8,387.1,446.2],
               '가을':[363.5,231.2,293.1,247.7,381.6],
               '겨울':[139.3,59.9,76.9,109.1,108.1]}
columns_list =['봄','여름','가을','겨울']
index_list = ['2012','2013','2014','2015','2016']

df3 = pd.DataFrame(table_data3, columns = columns_list, index= index_list)
df3

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [113]:
df3.mean()

봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64

In [114]:
df3.std()

봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64

In [115]:
df3.mean(axis=1)

2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64

In [116]:
df3.std(axis=1)

2012    274.472128
2013    211.128782
2014    221.150739
2015    114.166760
2016    146.548658
dtype: float64

In [117]:
df3.describe()

봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000

### 데이터를 원하는대로 선택하기

In [118]:
# import pandas as pd
# import numpy as np

# KTX_data = {'경부선 KTX':[39060]}

### 데이터 파일을 읽고 쓰기

In [129]:
%%writefile C:\myPyCode\data\sea_rain1.csv
연도, 동해, 남해, 서해, 전체
1996,17.4629,17.2288,14.436,15.9067
1997,17.4116,17.4092,14.8248,16.1526
1998,17.5944,18.011,15.2512,16.6044
1999,18.1495,18.3175,14.8979,16.6284
2000,17.9288,18.1766,15.0504,16.6178

Overwriting C:\myPyCode\data\sea_rain1.csv


In [130]:
import pandas as pd

pd.read_csv('C:/myPyCode/data/sea_rain1.csv')

연도       동해       남해       서해       전체
0  1996  17.4629  17.2288  14.4360  15.9067
1  1997  17.4116  17.4092  14.8248  16.1526
2  1998  17.5944  18.0110  15.2512  16.6044
3  1999  18.1495  18.3175  14.8979  16.6284
4  2000  17.9288  18.1766  15.0504  16.6178

In [132]:
pd.read_csv('C:/myPyCode/data/sea_rain1.csv', index_col= '연도')

동해       남해       서해       전체
연도                                      
1996  17.4629  17.2288  14.4360  15.9067
1997  17.4116  17.4092  14.8248  16.1526
1998  17.5944  18.0110  15.2512  16.6044
1999  18.1495  18.3175  14.8979  16.6284
2000  17.9288  18.1766  15.0504  16.6178

### 표 형식의 데이터를 파일로 쓰기

In [133]:
df_WH = pd.DataFrame({'Weight':[62,67,55,74],
                      'Height':[165,177,160,180]}, index = ['ID_1','ID_2','ID_3','ID_4'])
df_WH.index.name = 'User'
df_WH

Weight  Height
User                
ID_1      62     165
ID_2      67     177
ID_3      55     160
ID_4      74     180

In [135]:
bmi = df_WH['Weight']/(df_WH['Height']/100)**2
bmi

User
ID_1    22.773186
ID_2    21.385936
ID_3    21.484375
ID_4    22.839506
dtype: float64

In [136]:
df_WH['BMI'] = bmi
df_WH

Weight  Height        BMI
User                           
ID_1      62     165  22.773186
ID_2      67     177  21.385936
ID_3      55     160  21.484375
ID_4      74     180  22.839506

In [137]:
df_WH.to_csv('C:/myPyCode/data/save_DataFrame.csv')

In [138]:
!type C:\myPyCode\data\save_DataFrame.csv

User,Weight,Height,BMI
ID_1,62,165,22.77318640955005
ID_2,67,177,21.38593635289987
ID_3,55,160,21.484374999999996
ID_4,74,180,22.839506172839506


In [139]:
df_pr = pd.DataFrame({'판매가격':[2000,3000,5000,10000],
                      '판매량':[32,53,40,25]}, index = ['P1001','P1002','P1003','P1004'])
df_pr.index.name = '제품번호'
df_pr

판매가격  판매량
제품번호             
P1001   2000   32
P1002   3000   53
P1003   5000   40
P1004  10000   25

In [140]:
file_name = 'C:/myPyCode/data/save_DataFrame_cp949.txt'
df_pr.to_csv(file_name,sep=" ",encoding="cp949")

In [142]:
!type C:\myPyCode\data\save_DataFrame_cp949.txt

제품번호 판매가격 판매량
P1001 2000 32
P1002 3000 53
P1003 5000 40
P1004 10000 25
