In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
iris = datasets.load_iris() # 데이터 로드
features = iris.data[:100,:] #두 개의 클래스만 선택
target = iris.target[:100]
scaler = StandardScaler() # 특성을 표준화
features_standardized = scaler.fit_transform(features)
logistic_regression = LogisticRegression(random_state=0) # 로지스틱 회귀 모델 생성
model = logistic_regression.fit(features_standardized, target) # 모델 훈련
new_observation = [[.5, .5, .5, .5]] # 새로운 샘플 데이터 생성
model.predict(new_observation) # 클래스 예측


C:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([1])

In [4]:
model.predict_proba(new_observation) # 예측 확률 확인 --> class 1로 묶일 확률이 높다

array([[0.18944274, 0.81055726]])

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
iris = datasets.load_iris() # 데이터 로드
features = iris.data
target = iris.target
scaler = StandardScaler() # 특성을 표준화
features_standardized = scaler.fit_transform(features)
# OVR 로지스틱 회귀 모델을 만듭니다.
logistic_regression = LogisticRegression(random_state=0, multi_class="ovr")
model = logistic_regression.fit(features_standardized, target) # 모델 훈련
new_observation = [[.5, .5, .5, .5]] # 새로운 샘플 데이터 생성
model.predict(new_observation) # 클래스 예측

C:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([2])

In [6]:
model.predict_proba(new_observation) # 예측 확률 확인 --> class 2로 묶일 확률이 높다

array([[0.08401839, 0.29392375, 0.62205786]])

In [7]:
### 규제로 분산 줄이기

In [9]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
iris = datasets.load_iris() # 데이터를 로드
features = iris.data
target = iris.target
scaler = StandardScaler() # 특성을 표준화
features_standardized = scaler.fit_transform(features)
# 로지스틱 회귀 모델 객체 생성
logistic_regression = LogisticRegressionCV( penalty='l2', Cs=10, random_state=0, n_jobs=-1)
model = logistic_regression.fit(features_standardized, target) # 모델 훈련
logistic_regression.C_

C:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


array([4.64158883e-02, 2.78255940e+00, 1.29154967e+03])

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
iris = datasets.load_iris() # 데이터 로드
features = iris.data
target = iris.target
scaler = StandardScaler() # 특성 표준화
features_standardized = scaler.fit_transform(features)
# 로지스틱 회귀 모델 생성
logistic_regression = LogisticRegression(random_state=0, solver="sag")
model = logistic_regression.fit(features_standardized, target) # 모델 훈련

C:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [13]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
iris = datasets.load_iris() # 데이터 로드
features = iris.data
target = iris.target
features = features[40:,:] # 처음 40개 샘플을 제거
target = target[40:] #불균형한 클래스를 만듭니다.
# 타깃 벡터에서 0이 아닌 클래스는 모두 1로 만듭니다.
target = np.where((target == 0), 0, 1)
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features) # 특성을 표준화
# 로지스틱 회귀 모델 생성
logistic_regression = LogisticRegression(random_state=0, class_weight="balanced")
model = logistic_regression.fit(features_standardized, target) # 모델 훈련

C:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


 ## 로지스틱 회귀 분류
 1. load_breast_cancer()
 2. 특성을 표준화
 3. 학습,테스트 데이터 분리
 4. 로지스틱 회귀 알고리즘 객체 생성된
 5. 학습
 6. 테스트 데이터로 예측값
 7. 평가(정확도와 ROC_AUC 출력)
    params = {'penalty':['l2','l1'],
     'C':[0.01,0.1,1,5,10]}
 8. GridSearchCV 사용해서 최적의 하이퍼 파라미터 찾아 출력
    최적의 하이퍼 파라미터일때 정확도도 출력하고 

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
iris = datasets.load_iris() # 데이터 로드
features = iris.data
target = iris.target
scaler = StandardScaler() # 특성을 표준화
features_standardized = scaler.fit_transform(features)
# OVR 로지스틱 회귀 모델을 만듭니다.
logistic_regression = LogisticRegression(random_state=0, multi_class="ovr")
model = logistic_regression.fit(features_standardized, target) # 모델 훈련
new_observation = [[.5, .5, .5, .5]] # 새로운 샘플 데이터 생성
model.predict(new_observation) # 클래스 예측

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
import pandas as pd

cancer = datasets.load_breast_cancer()
features = cancer.data
target = cancer.target
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)
